---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-stocks-producer
  name: kafka-stocks-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: kafka-stocks-producer
      app: kafka-stocks-producer
  template:
    metadata:
      labels:
        deployment: kafka-stocks-producer
        app: kafka-stocks-producer
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          image: quay.io/btison/quarkus-kafka-stocks-producer:latest
          imagePullPolicy: IfNotPresent
          name: kafka-stocks-producer
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 3
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            limits:
              cpu: 500m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /deployments/config
              name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: kafka-stocks-producer
          name: config
